# permissions for end users to edit downstreamranchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: downstreamrancher-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: platform-controller
    app.kubernetes.io/part-of: platform-controller
    app.kubernetes.io/managed-by: kustomize
  name: downstreamrancher-editor-role
rules:
- apiGroups:
  - platform.rubyrainbows.com
  resources:
  - downstreamranchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.rubyrainbows.com
  resources:
  - downstreamranchers/status
  verbs:
  - get
